### ISSUE TITLE
Keep getting errors on fresh install

### ISSUE THREAD

**Issue by mattiasghodsian** [jkread/arkserver#10]
log
```
Attaching to ark_TheIsland
[0m ###########################################################################
[0m # Ark Server -  Sun Apr 24 11:37:43 Europe 2022
[0m ###########################################################################
[0m Ensuring correct permissions...
[0m Cleaning up any leftover arkmanager files...
[0m Creating arkmanager.cfg from environment variables...
[0m No game files found. Installing...
[0m Running command 'install' for instance 'main'
[0m Installing ARK serverExecuting /home/steam/.steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /ark/server +app_update 376030 validate +quit
[0m Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[0m Looks like steam didn't shutdown cleanly, scheduling immediate update check
[0m [  0%] Checking for available updates...
[0m [----] Verifying installation...
[0m Steam Console Client (c) Valve Corporation - version 1648077083
[0m -- type 'quit' to exit --
[0m Loading Steam API...OK
[0m "@NoPromptForPassword" = "1"
[0m [0m
[0m Connecting anonymously to Steam Public...OK
[0m Waiting for client config...OK
[0m Waiting for user info...OK
[0m [33;1mPlease use force_install_dir before logon!
[0m [0m Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
[0m  Update state (0x5) verifying install, progress: 10.21 (1839051863 / 18006952591)
[0m Error! App '376030' state is 0x202 after update job.
[0m Creating crontab...
[0m Starting cron service...
[0m  * Starting periodic command scheduler cron
[0m    ...done.
[0m Loading crontab...
[0m Save file validation is not enabled.
[0m [No Backup On Start]
[0m /arkserver/arkserver.sh: line 121: [: -eq: unary operator expected
[0m /arkserver/arkserver.sh: line 153: [: -eq: unary operator expected
[0m Running command 'start' for instance 'main'
[0m [ [0;33m WARN [0;39m ] 	Your ARK server exec could not be found.
[0m Checking for updates before starting
[0m Checking for update; PID: 75
[0m Copying to staging directory
[0m cp: cannot stat '/ark/server/Engine/.': No such file or directory
[0m cp: cannot stat '/ark/server/linux64/.': No such file or directory
[0m cp: cannot stat '/ark/server/ShooterGame/Content/Mods/111111111/.': No such file or directory
[0m cp: cannot stat '/ark/server/ShooterGame/Content/Mods/111111111.mod': No such file or directory
[0m Downloading ARK updateExecuting /home/steam/.steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /ark/staging +app_update 376030 +quit
[0m Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[0m [  0%] Checking for available updates...
[0m [----] Verifying installation...
[0m Steam Console Client (c) Valve Corporation - version 1648077083
[0m -- type 'quit' to exit --
[0m Loading Steam API...OK
[0m "@NoPromptForPassword" = "1"
[0m [0m
[0m Connecting anonymously to Steam Public...OK
[0m Waiting for client config...OK
[0m Waiting for user info...OK
[0m [33;1mPlease use force_install_dir before logon!
[0m [0m Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
[0m  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
[0m Error! App '376030' state is 0x202 after update job.
[0m Update download interrupted
[0m The server is starting...
[0m 
[0m An update is currently in progress.  Start aborted
[0m Cleaning up any leftover arkmanager files...
[0m Creating arkmanager.cfg from environment variables...
[0m No game files found. Installing...
[0m Running command 'install' for instance 'main'
[0m Installing ARK serverExecuting /home/steam/.steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /ark/server +app_update 376030 validate +quit
[0m Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[0m [  0%] Checking for available updates...
[0m [----] Verifying installation...
[0m Steam Console Client (c) Valve Corporation - version 1648077083
[0m -- type 'quit' to exit --
[0m Loading Steam API...OK
[0m "@NoPromptForPassword" = "1"
[0m [0m
[0m Connecting anonymously to Steam Public...OK
[0m Waiting for client config...OK
[0m Waiting for user info...OK
[0m [33;1mPlease use force_install_dir before logon!
[0m [0m Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
[0m  Update state (0x5) verifying install, progress: 91.71 (16513451079 / 18006952591)
[0m Error! App '376030' state is 0x202 after update job.
[0m Starting cron service...
[0m  * Starting periodic command scheduler cron
[0m    ...done.
[0m Loading crontab...
[0m Save file validation is not enabled.
[0m /arkserver/arkserver.sh: line 121: [: -eq: unary operator expected
[0m [No Backup On Start]
[0m /arkserver/arkserver.sh: line 153: [: -eq: unary operator expected
[0m Running command 'start' for instance 'main'
[0m [ [0;33m WARN [0;39m ] 	Your ARK server exec could not be found.
[0m Checking for updates before starting
[0m Checking for update; PID: 76

```

docker-compose.yml
```yml
version: '3'
volumes:
  ark:
  steam:
services:
  ark_TheIsland:
    image: jkread/arkserver:latest
    container_name: ark_TheIsland
    network_mode: bridge
    restart: always
    ports:
      - 7777:7777
      - 7777:7777/udp
      - 7778:7778
      - 7778:7778/udp
      - 27018:27015
      - 27018:27015/udp
    volumes:
      - ./data/ark:/ark
      - ./data/steam:/home/steam
    environment:
      - TZ=Europe/Stocholm
      - am_ark_SessionName=Lost Fury - TheIsland
      - am_serverMap=TheIsland
      - am_ark_ServerPassword=hejsan
      - am_ark_ServerAdminPassword=wdv365365
      - am_ark_MaxPlayers=70
      - am_ark_QueryPort=27015
      - am_ark_Port=7778
      - am_ark_RCONPort=32330
      - am_arkwarnminutes=15
      - am_arkAutoUpdateOnStart=true
      - am_arkBackupPreUpdate=true
      - am_arkMaxBackupSizeMB=500
      - am_arkflag_crossplay=false
      - am_arkflag_NoBattlEye=true
      # - am_ark_GameModIds=111111111,566885854,731604991,761535755,821530042,889745138,1404697612
```
